logging:
  # Python logging config (passed to dictConfig)
  version: 1
  formatters:
    default:
      format: '[%(asctime)s] %(levelname)s in %(name)s:%(lineno)s: %(message)s'
  handlers:
    wsgi:
      level: INFO
      formatter: default
      class: logging.StreamHandler
      stream: 'ext://flask.logging.wsgi_errors_stream'
    log_file:
      level: DEBUG
      formatter: default
      class: logging.handlers.RotatingFileHandler
      filename: 'logs/server.log'
      mode: 'a'
      maxBytes: 67108864  # 64 MB
      backupCount: 10
  loggers:
    # root logger
    '':
      level: INFO
      handlers:
        - wsgi
        - log_file
    pygrobid:
      level: DEBUG
    __main__:
      level: DEBUG
    delft:
      level: INFO
    sciencebeam_trainer_delft:
      level: INFO
pdfalto:
  path: https://github.com/kermitt2/pdfalto/files/6104204/pdfalto-4b4e983413278a07bb4cc4b2836de03adc8ca6dc-dockcross-linux-64.gz
models:
  segmentation:
    path: 'https://github.com/elifesciences/sciencebeam-models/releases/download/biorxiv-grobid/2021-05-11-delft-grobid-segmentation-biorxiv-10k-auto-v0.0.23-train-1966-e133.tar.gz'
  header:
    path: 'https://github.com/elifesciences/sciencebeam-models/releases/download/v0.0.1/2020-10-04-delft-grobid-header-biorxiv-no-word-embedding.tar.gz'
  fulltext:
    path: 'https://github.com/elifesciences/sciencebeam-models/releases/download/biorxiv-grobid/2021-05-11-delft-grobid-fulltext-biorxiv-10k-auto-v0.0.21-train-1986-e159.tar.gz'
