version: '3'

# used by default but not in ci
services:
    sciencebeam:
        depends_on:
            - grobid

    sciencebeam-dev:
        volumes:
        - ./sciencebeam:/srv/sciencebeam/sciencebeam
        environment:
            # avoid issues with .pyc/pyo files when mounting source directory
            PYTHONOPTIMIZE: ""
            PYTHONDONTWRITEBYTECODE: "1"
