name: Python package

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
        include:
        - python-version: 3.8
          push-package: true
        - os: windows-latest
          python-version: 3.8
        - os: macos-latest
          python-version: 3.8

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make dev-venv SYSTEM_PYTHON=python
      - name: Lint
        run: |
          make dev-lint
      - name: Test with pytest
        run: |
          make dev-pytest
